# Generated by Django 5.2 on 2025-06-12 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_cartitem_variant_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='date_of_birth',
        ),
    ]
