# Generated by Django 5.2 on 2025-06-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_address_alternate_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='alternate_mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='mobile_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.CharField(max_length=20),
        ),
    ]
