# Generated by Django 5.2 on 2025-06-14 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order_order_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
