# Generated by Django 5.2 on 2025-06-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_orderitem_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(default='Confirmed', max_length=50),
        ),
    ]
