# Generated by Django 5.2 on 2025-06-15 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_orderitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
    ]
