# Generated by Django 5.2 on 2025-06-12 15:19

import back_office.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0004_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Upload a profile image (JPG, JPEG, PNG only)', null=True, upload_to=back_office.models.user_profile_image_path),
        ),
    ]
