# Generated by Django 5.2 on 2025-06-19 05:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0005_alter_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique coupon code (e.g., SAVE10)', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the coupon')),
                ('coupon_type', models.CharField(choices=[('percentage', 'Percentage Discount'), ('fixed', 'Fixed Amount Discount')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Discount amount or percentage', max_digits=10)),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum order amount to apply coupon', max_digits=10)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount cap for percentage coupons', max_digits=10, null=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, help_text='Coupon validity start date')),
                ('valid_until', models.DateTimeField(help_text='Coupon validity end date')),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Maximum number of times coupon can be used', null=True)),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of times coupon has been used')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the coupon is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
